# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  - nodejs_version: "6"

install:
  - netsh advfirewall firewall add rule name="Open Port 8008" dir=in action=allow protocol=TCP localport=8008
  - npm install -g purplecabbage/cordova-paramedic
  - npm install -g cordova

build: off

test_script:
  - node --version
  - npm --version
  - msbuild /version
  - cordova --version
  - cordova-paramedic --platform android